# Generated by Django 4.0.6 on 2022-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_alter_todolist_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='task_order',
        ),
        migrations.AddField(
            model_name='todolist',
            name='tasks',
            field=models.JSONField(default={'tasks': []}, verbose_name='Список задач'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
