# Generated by Django 4.0.6 on 2022-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0003_remove_todolist_task_order_todolist_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='Новый список', max_length=100, verbose_name='Название'),
        ),
    ]
