# Generated by Django 4.0.6 on 2022-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0004_todolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='Новый список', max_length=20, verbose_name='Название'),
        ),
    ]
