# Generated by Django 4.0.6 on 2022-07-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0005_alter_todolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tasks',
            field=models.JSONField(default={'tasks': {}}, verbose_name='Список задач'),
        ),
    ]
