# Generated by Django 4.0.6 on 2022-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0006_alter_todolist_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='Новый список', max_length=30, verbose_name='Название'),
        ),
    ]
